"use client"
import './globals.css'
// import styles from '../sidebar.css'
// import Link from 'next/link';
import UserProvider from './providers/UserProvider'
import NextProvider from './providers/NextProvider';

import Navibar from '../components/Navbar'
import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

function RootLayout({ children }) {
  return (
    <UserProvider>
    {/* <NoSsrWrapper> */}

    <html lang="en">
      <body  suppressHydrationWarning={true}>
      <NextProvider>
        <Navibar/>
        {children}
        </NextProvider>
        </body>
    </html>

    {/* </NoSsrWrapper> */}
    </UserProvider>
  )
}

export default RootLayout